#ifndef GUARD_CONSTANTS_EVEN_CRAFTING_CONSTANTS_H
#define GUARD_CONSTANTS_EVEN_CRAFTING_CONSTANTS_H

enum Recipe {
    RECIPE_LEVEL_BALL,
    RECIPE_LURE_BALL,
    RECIPE_MOON_BALL,
    RECIPE_FRIEND_BALL,
    RECIPE_LOVE_BALL,
    RECIPE_FAST_BALL,
    RECIPE_HEAVY_BALL,
    RECIPE_ABILITY_CAPSULE,
    RECIPE_ABILITY_PATCH,
    //  RECIPE_NONE must after all actual recipes
    RECIPE_NONE,
    ERROR_MISSING_INGREDIENTS,
    ERROR_RECIPE_REQUIRES_UNLOCK,
};

enum RecipeCategory {
    RECIPE_CATEGORY_POKEBALLS,
    RECIPE_CATEGORY_SPECIAL,
    //  Must be last
    NUM_RECIPE_CATEGORIES
};

#endif
