#ifndef GUARD_CONSTANTS_EVEN_CRAFTING_CONSTANTS_H
#define GUARD_CONSTANTS_EVEN_CRAFTING_CONSTANTS_H

enum Recipe {
    RECIPE_POKE_BALL,
    RECIPE_POTION,
    RECIPE_SUPER_POTION,
    //  RECIPE_NONE must after all actual recipes
    RECIPE_NONE,
    ERROR_MISSING_INGREDIENTS,
    ERROR_RECIPE_REQUIRES_UNLOCK,
};

enum RecipeCategory {
    RECIPE_CATEGORY_POKEBALLS,
    RECIPE_CATEGORY_MEDICINE,
    //  Must be last
    NUM_RECIPE_CATEGORIES
};

#endif
