#ifndef GUARD_CONSTANTS_DAY_NIGHT_H
#define GUARD_CONSTANTS_DAY_NIGHT_H

#define OVERRIDE_PALETTE_NONE  0
#define OVERRIDE_PALETTE_NIGHT 1
#define OVERRIDE_PALETTE_DAY   2

#endif  // GUARD_CONSTANTS_DAY_NIGHT_H